### ISSUE TITLE
Package.json Script Command for NPM Publish

### ISSUE THREAD

**Issue by WrathChaos** [Paraboly/pwc-web-component-boilerplate#5]
We need a script command for build -> test -> publish. I sometimes forgot to build and publish the library. There is a working example on **PermissionService** Library.

**Comment by starikcetin** [comment]
Implemented, needs review @WrathChaos

**Comment by WrathChaos** [comment]
@starikcetin love it! Have you ever tested it? Also, Boilerplate's README is broken :) Good job!

**Comment by starikcetin** [comment]
I did test it but honestly, I have no idea what some of the commands do.

I broke the readme on purpose. all project name instances are "project-name" or "ProjectName" and all component name instances are "component-name" or "ComponentName". This makes it easier to do refactoring in one go.

**Comment by WrathChaos** [comment]
Still, we can make it with mass renaming feature :) We can work together for the commands :) Remind me for that, please. @starikcetin
